table BasketAffinity
	lineageTag: b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6f

	column SubcategoryA
		dataType: string
		lineageTag: c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7a
		summarizeBy: none
		sourceColumn: SubcategoryA

	column SubcategoryB
		dataType: string
		lineageTag: d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8b
		summarizeBy: none
		sourceColumn: SubcategoryB

	column Orders
		dataType: int64
		lineageTag: e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9c
		summarizeBy: sum
		sourceColumn: Orders

	column SupportPct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0d
		summarizeBy: sum
		sourceColumn: SupportPct

		annotation SummarizationSetBy = Automatic

	column ConfidenceAtoB
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1e
		summarizeBy: sum
		sourceColumn: ConfidenceAtoB

		annotation SummarizationSetBy = Automatic

	column Lift
		dataType: double
		formatString: 0.0"x"
		lineageTag: b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2f
		summarizeBy: sum
		sourceColumn: Lift

		annotation SummarizationSetBy = Automatic

	partition BasketAffinity = m
		mode: import
		source =
				let
					Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorks2022"),
					Data = Source{[Schema="pbi",Item="BasketAffinity"]}[Data],
					#"Divided Pct" = Table.TransformColumns(Data, {{"SupportPct", each _ / 100, type number}, {"ConfidenceAtoB", each _ / 100, type number}})
				in
					#"Divided Pct"

