table CohortRetentionSummary
	lineageTag: d8e9f0a1-b2c3-4d4e-5f6a-7b8c9d0e1f2a

	column CohortGroup
		dataType: string
		lineageTag: e9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3b
		summarizeBy: none
		sourceColumn: CohortGroup

	column MonthsSinceFirstOrder
		dataType: int64
		lineageTag: f0a1b2c3-d4e5-4f6a-7b8c-9d0e1f2a3b4c
		summarizeBy: none
		sourceColumn: MonthsSinceFirstOrder

	column RetentionPct
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5e
		summarizeBy: sum
		sourceColumn: RetentionPct

		annotation SummarizationSetBy = Automatic

	partition CohortRetentionSummary = m
		mode: import
		source =
				let
					Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorks2022"),
					Data = Source{[Schema="pbi",Item="CohortRetentionSummary"]}[Data],
					#"Divided Pct" = Table.TransformColumns(Data, {{"RetentionPct", each _ / 100, type number}})
				in
					#"Divided Pct"

