table RepeatPurchaseSegments
	lineageTag: b0c1d2e3-f4a5-4b6c-7d8e-9f0a1b2c3d4e

	column Segment
		dataType: string
		lineageTag: c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f
		summarizeBy: none
		sourceColumn: Segment

	column Customers
		dataType: int64
		lineageTag: d2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a
		summarizeBy: sum
		sourceColumn: Customers

	column PctOfCustomers
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e3f4a5b6-c7d8-4e9f-0a1b-2c3d4e5f6a7b
		summarizeBy: sum
		sourceColumn: PctOfCustomers

		annotation SummarizationSetBy = Automatic

	partition RepeatPurchaseSegments = m
		mode: import
		source =
				let
					Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorks2022"),
					Data = Source{[Schema="pbi",Item="RepeatPurchaseSegments"]}[Data],
					#"Divided Pct" = Table.TransformColumns(Data, {{"PctOfCustomers", each _ / 100, type number}})
				in
					#"Divided Pct"

